# Generated by Django 4.1.1 on 2022-09-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onememos", "0002_alter_memo_memo_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memo", name="memo_text", field=models.CharField(max_length=200),
        ),
    ]
